# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab6f34a3eb33b99ede1f2da6c1a04ac9430e3b5b9ba74d76fd6b84bc2ec6c6874ff6b03e474f92fa847d66ef706e1a75b4908d009152bd1d096ae1100ed54441

test:
  secret_key_base: 458966c7272e444e81f5832640cc3616451d0aa5bde5ce96d9bab02b0da91b0ad3a15b1f069d05b8e6a6e30ea52d0dc1842ff1905766d6baaa03e07c6a6c87c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
